spring.application.name=vebbleAi
gemini.api.key=${GEMINI_KEY}
gemini.api.url=${GEMINI_URL}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

server.port=${PORT:8080}


