spring:
  application:
    name: vebbleAi
  graphql:
    http:
      path: /api/games/sudoku-app
    webmvc:
      get:
        enabled: true
    graphiql:
      enabled: true
      path: /graphql
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,OPTIONS"
      allowed-headers: "*"

gemini:
  api:
    url: ${GEMINI_URL}
    key1: ${GEMINI_KEY1}
    key2: ${GEMINI_KEY2}
    key3: ${GEMINI_KEY3}

sarvam:
  api:
    url: ${SARVAM_URL}
    key: ${SARVAM_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

server:
  port: ${PORT:8080}

